config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :comments_counter
  after_destroy :comments_counter

  private

  def comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :likes_counter
  after_destroy :likes_counter

  private

  def likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true, length: { maximum: 1000 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :post_counter
  after_destroy :post_counter

  def recent_comments
    comments.last(5)
  end

  private

  def post_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.last(3).reverse
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create], if: -> { request.format.json? }

  def index
    post = Post.find_by_id(params[:post_id])
    comments = post.comments

    render json: comments
  end

  def create
    user = User.find_by_id(params[:user_id])
    post = Post.find_by_id(params[:post_id])
    comment = post.comments.new(comment_params)
    comment.author = user

    if comment.save
      render json: { success: 'Comment created successfully' }
    else
      render json: { errors: comment.errors.full_messages }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts

    render json: posts
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user

    if @comment.save
      flash[:success] = 'Comment added!'
      redirect_to user_post_path(current_user, @comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find_by_id(params[:post_id])
    @like = @post.likes.new(author: current_user)

    if @like.save
      flash[:success] = 'Like added!'
      redirect_to user_post_path(current_user, @like.post)
    else
      flash[:errors] = @like.errors.full_messages
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find_by_id(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find_by_id(params[:user_id])
    @post = Post.find_by_id(params[:id])
    @current_user = current_user
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.persisted?
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='template'>
  <%= render partial: 'shared/user-container', locals: { user: @user } %>
  <% @posts.each do |post| %>
    <div class='post-container'>
      <%= render partial: 'shared/post', locals: { user: @user, post: post }%>
      <div class='recent_comments'>
        <% post.recent_comments.each do |comment| %>
          <p><%= comment.author.name%>:<%= comment.text%></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Add post details</h1>
<%= form_with model: @post, local: true, data: { turbo: false }, url: user_posts_path do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_area :text, size: "70x5" %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
  <%= @post.errors.full_messages.first if @post.errors.any? %>
<% end %>

app/views/posts/show.html.erb
<div class='template'>
  <h1>@<%= @user.name %></h1>
  <%= render partial: 'shared/post', locals: { user: @user, post: @post } %>
  <div>
    <% @post.comments.each do |comment| %>
      <p><%= comment.author.name%>:<%= comment.text%></p>
    <% end %>
  </div>
  <%= form_with model: [@user, @post.comments.new], url: user_post_comments_url(@user, @post), local: true do |f| %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.text_area :text %>
    <%= f.submit 'Comment' %>
  <% end %>
  <%= form_with model:[@user, @post.likes.new], url: user_post_likes_url(@user,@post), local: true do |f| %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <%= f.submit 'Like' %>
  <% end %>
  <button type='button'>
    <%= link_to 'Go back to profile', user_url(@current_user) %>
  </button>
</div>

app/views/shared/_post.html.erb
<div>
  <h3><%= link_to post.title, user_post_url(user, post) %></h3>
  <p><%= post.text %></p>
  <small>Comments:<%= post.comments_counter %>, Likes:<%= post.likes_counter %></small>
</div>

app/views/shared/_user-container.html.erb
<div class='user-container'>
  <img src="<%= user.photo%>" class='user-img' />
  <div class='user-div'>
    <h2><%= user.name %></h2>
    <small class='posts_counter'>Number of posts: <%= user.posts_counter %></small>
  </div>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, 'data-turbo-method': :delete %>
  <div class='template'>
  <% @users.each do |user| %>
    <div class='user-container'>
      <img src="<%= user.photo%>" class='user-img' />
      <div class='user-div'>
        <h2><%= link_to user.name, user_url(user) %></h2>
        <small class='posts_counter'>Number of posts: <%= user.posts_counter %></small>
      </div>
    </div>
  <% end %>
  </div>
<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/users/show.html.erb
<div class='template'>
  <%= render partial: 'shared/user-container', locals: { user: @user } %>
  <div><%= @user.bio %></div>
  <button type='button'>
    <%= link_to "Create new post", new_user_post_url(@current_user) %>
  </button>
  <% @user.recent_posts.each do |post| %>
    <%= render partial: 'shared/post', locals: { user: @user, post: post } %>
  <% end %>
  <div class='button-wrapper'>
    <button type="button" class='see-posts-btn'>
      <%= link_to "See all posts", user_posts_url(@user) %>
    </button>
  </div>
</div>